//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz
    {
        public Quiz()
        {
            this.Question = new HashSet<Question>();
            this.QuizHistory = new HashSet<QuizHistory>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public int Completed { get; set; }
    
        public virtual ICollection<Question> Question { get; set; }
        public virtual ICollection<QuizHistory> QuizHistory { get; set; }
    }
}
