//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizHistory
    {
        public QuizHistory()
        {
            this.QuizHistoryDetail = new HashSet<QuizHistoryDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> QuizID { get; set; }
        public int Completed { get; set; }
        public Nullable<double> CorrectPercentage { get; set; }
    
        public virtual Quiz Quiz { get; set; }
        public virtual ICollection<QuizHistoryDetail> QuizHistoryDetail { get; set; }
    }
}
